import { eq } from 'drizzle-orm';

import { dictConfigs } from '../schemas/dictConfigs';
import type { LobeChatDatabase } from '../type';

export interface DictConfigDefault {
  key: string;
  value: string | number | boolean | unknown;
  label: string;
  group: string;
  type: 'string' | 'number' | 'boolean' | 'json';
  sort: number;
  description?: string;
  enabled: boolean;
}

/**
 * Group display names (Chinese labels) for dictionary configuration categories.
 */
export const DICT_CONFIG_GROUPS: Record<string, string> = {
  system_settings: '系统设置',
  payment_settings: '支付设置',
  membership_settings: '会员权益',
  feature_flags: '功能开关',
  ai_settings: 'AI 模型设置',
  content_settings: '内容审核',
  ui_settings: '界面设置',
  security_settings: '安全设置',
  notification_settings: '通知设置',
  storage_settings: '存储设置',
  integration_settings: '集成设置',
  rate_limits: '速率限制',
  other_settings: '其他设置',
};

export const DEFAULT_DICT_CONFIGS: DictConfigDefault[] = [
  // ============== System Settings ==============
  {
    key: 'systemName',
    value: 'LobeHub',
    label: '系统名称',
    group: 'system_settings',
    type: 'string',
    sort: 1,
    description: '显示在页面标题和登录页的系统名称',
    enabled: true,
  },
  {
    key: 'systemLogo',
    value: '',
    label: '系统Logo URL',
    group: 'system_settings',
    type: 'string',
    sort: 2,
    description: '自定义系统Logo图片地址',
    enabled: true,
  },
  {
    key: 'systemDescription',
    value: 'AI Agent 协作平台',
    label: '系统描述',
    group: 'system_settings',
    type: 'string',
    sort: 3,
    description: '系统简介，显示在登录页和SEO描述中',
    enabled: true,
  },
  {
    key: 'defaultLanguage',
    value: 'zh-CN',
    label: '默认语言',
    group: 'system_settings',
    type: 'string',
    sort: 4,
    description: '新用户首次访问时的默认语言',
    enabled: true,
  },
  {
    key: 'registrationEnabled',
    value: true,
    label: '允许注册',
    group: 'system_settings',
    type: 'boolean',
    sort: 5,
    description: '是否允许新用户注册账号',
    enabled: true,
  },
  {
    key: 'emailVerificationRequired',
    value: false,
    label: '邮箱验证',
    group: 'system_settings',
    type: 'boolean',
    sort: 6,
    description: '注册后是否需要验证邮箱才能使用',
    enabled: true,
  },
  {
    key: 'maxWorkspacesPerUser',
    value: 5,
    label: '单用户最大空间数',
    group: 'system_settings',
    type: 'number',
    sort: 7,
    description: '每个用户最多可以创建多少个工作空间',
    enabled: true,
  },
  {
    key: 'maxFileUploadSize',
    value: 50,
    label: '最大文件上传大小(MB)',
    group: 'system_settings',
    type: 'number',
    sort: 8,
    description: '用户上传文件的最大限制',
    enabled: true,
  },
  {
    key: 'guestModeEnabled',
    value: false,
    label: '访客模式',
    group: 'system_settings',
    type: 'boolean',
    sort: 9,
    description: '是否允许未登录用户使用基础功能',
    enabled: true,
  },
  {
    key: 'defaultUserRole',
    value: 'free_user',
    label: '新用户默认角色',
    group: 'system_settings',
    type: 'string',
    sort: 10,
    description: '新注册用户默认分配的系统角色',
    enabled: true,
  },

  // ============== Payment Settings ==============
  {
    key: 'creditsExchangeRate',
    value: 100,
    label: '积分兑换比例',
    group: 'payment_settings',
    type: 'number',
    sort: 1,
    description: '1元兑换多少积分',
    enabled: true,
  },
  {
    key: 'minTopUpAmount',
    value: 10,
    label: '最低充值金额(元)',
    group: 'payment_settings',
    type: 'number',
    sort: 2,
    description: '用户充值的最低金额限制',
    enabled: true,
  },
  {
    key: 'maxTopUpAmount',
    value: 10000,
    label: '最高充值金额(元)',
    group: 'payment_settings',
    type: 'number',
    sort: 3,
    description: '用户单次充值的最高金额限制',
    enabled: true,
  },
  {
    key: 'refundEnabled',
    value: true,
    label: '允许退款',
    group: 'payment_settings',
    type: 'boolean',
    sort: 4,
    description: '是否允许用户申请退款',
    enabled: true,
  },
  {
    key: 'refundDeadlineDays',
    value: 7,
    label: '退款期限(天)',
    group: 'payment_settings',
    type: 'number',
    sort: 5,
    description: '支付后多少天内可申请退款',
    enabled: true,
  },
  {
    key: 'autoIssueInvoice',
    value: false,
    label: '自动开票',
    group: 'payment_settings',
    type: 'boolean',
    sort: 6,
    description: '支付完成后是否自动开具发票',
    enabled: true,
  },
  {
    key: 'invoiceTaxRate',
    value: 6,
    label: '发票税率(%)',
    group: 'payment_settings',
    type: 'number',
    sort: 7,
    description: '发票税率百分比',
    enabled: true,
  },

  // ============== Membership Benefits ==============
  {
    key: 'freeUserDailyLimit',
    value: 10,
    label: '免费用户每日对话限制',
    group: 'membership_settings',
    type: 'number',
    sort: 1,
    description: '免费用户每天最多发起多少次对话',
    enabled: true,
  },
  {
    key: 'freeUserFileLimit',
    value: 5,
    label: '免费用户文件数量限制',
    group: 'membership_settings',
    type: 'number',
    sort: 2,
    description: '免费用户最多上传多少个文件',
    enabled: true,
  },
  {
    key: 'freeUserStorageLimit',
    value: 100,
    label: '免费用户存储空间(MB)',
    group: 'membership_settings',
    type: 'number',
    sort: 3,
    description: '免费用户的文件存储空间限制',
    enabled: true,
  },
  {
    key: 'proUserDailyLimit',
    value: 100,
    label: 'Pro用户每日对话限制',
    group: 'membership_settings',
    type: 'number',
    sort: 4,
    description: 'Pro用户每天最多发起多少次对话',
    enabled: true,
  },
  {
    key: 'proUserFileLimit',
    value: 50,
    label: 'Pro用户文件数量限制',
    group: 'membership_settings',
    type: 'number',
    sort: 5,
    description: 'Pro用户最多上传多少个文件',
    enabled: true,
  },
  {
    key: 'proUserStorageLimit',
    value: 2048,
    label: 'Pro用户存储空间(MB)',
    group: 'membership_settings',
    type: 'number',
    sort: 6,
    description: 'Pro用户的文件存储空间限制',
    enabled: true,
  },
  {
    key: 'vipUserDailyLimit',
    value: -1,
    label: 'VIP用户每日对话限制',
    group: 'membership_settings',
    type: 'number',
    sort: 7,
    description: 'VIP用户每天最多发起多少次对话(-1表示无限制)',
    enabled: true,
  },
  {
    key: 'vipUserFileLimit',
    value: -1,
    label: 'VIP用户文件数量限制',
    group: 'membership_settings',
    type: 'number',
    sort: 8,
    description: 'VIP用户最多上传多少个文件(-1表示无限制)',
    enabled: true,
  },
  {
    key: 'vipUserStorageLimit',
    value: 10240,
    label: 'VIP用户存储空间(MB)',
    group: 'membership_settings',
    type: 'number',
    sort: 9,
    description: 'VIP用户的文件存储空间限制',
    enabled: true,
  },
  {
    key: 'vipPrioritySupport',
    value: true,
    label: 'VIP优先客服',
    group: 'membership_settings',
    type: 'boolean',
    sort: 10,
    description: 'VIP用户是否享受优先客服支持',
    enabled: true,
  },

  // ============== Feature Flags ==============
  {
    key: 'enableAgentMarket',
    value: true,
    label: 'Agent 市场',
    group: 'feature_flags',
    type: 'boolean',
    sort: 1,
    description: '是否开启Agent发现页/市场功能',
    enabled: true,
  },
  {
    key: 'enableKnowledgeBase',
    value: true,
    label: '知识库功能',
    group: 'feature_flags',
    type: 'boolean',
    sort: 2,
    description: '是否开启知识库功能',
    enabled: true,
  },
  {
    key: 'enableImageGeneration',
    value: true,
    label: '图片生成',
    group: 'feature_flags',
    type: 'boolean',
    sort: 3,
    description: '是否开启AI图片生成功能',
    enabled: true,
  },
  {
    key: 'enablePluginSystem',
    value: true,
    label: '插件系统',
    group: 'feature_flags',
    type: 'boolean',
    sort: 4,
    description: '是否开启插件/技能功能',
    enabled: true,
  },
  {
    key: 'enableVoiceChat',
    value: false,
    label: '语音对话',
    group: 'feature_flags',
    type: 'boolean',
    sort: 5,
    description: '是否开启语音对话功能',
    enabled: true,
  },
  {
    key: 'enableTaskScheduler',
    value: true,
    label: '任务调度',
    group: 'feature_flags',
    type: 'boolean',
    sort: 6,
    description: '是否开启Agent任务调度功能',
    enabled: true,
  },
  {
    key: 'enableShareSession',
    value: true,
    label: '对话分享',
    group: 'feature_flags',
    type: 'boolean',
    sort: 7,
    description: '是否允许用户分享对话链接',
    enabled: true,
  },
  {
    key: 'enableTeamCollaboration',
    value: true,
    label: '团队协作',
    group: 'feature_flags',
    type: 'boolean',
    sort: 8,
    description: '是否开启工作空间团队协作功能',
    enabled: true,
  },
  {
    key: 'enableCustomBranding',
    value: false,
    label: '自定义品牌',
    group: 'feature_flags',
    type: 'boolean',
    sort: 9,
    description: '是否允许企业版用户自定义品牌标识',
    enabled: true,
  },
  {
    key: 'enableSsoLogin',
    value: false,
    label: 'SSO 单点登录',
    group: 'feature_flags',
    type: 'boolean',
    sort: 10,
    description: '是否开启SSO单点登录功能',
    enabled: true,
  },

  // ============== AI Model Settings ==============
  {
    key: 'defaultModel',
    value: 'gpt-4o',
    label: '默认AI模型',
    group: 'ai_settings',
    type: 'string',
    sort: 1,
    description: '新用户默认使用的AI模型',
    enabled: true,
  },
  {
    key: 'defaultTemperature',
    value: 0.7,
    label: '默认温度',
    group: 'ai_settings',
    type: 'number',
    sort: 2,
    description: '新用户默认的采样温度(0-2)',
    enabled: true,
  },
  {
    key: 'maxContextTokens',
    value: 8000,
    label: '最大上下文Token数',
    group: 'ai_settings',
    type: 'number',
    sort: 3,
    description: '单次对话最大上下文Token数量限制',
    enabled: true,
  },
  {
    key: 'maxOutputTokens',
    value: 4000,
    label: '最大输出Token数',
    group: 'ai_settings',
    type: 'number',
    sort: 4,
    description: '单次回复最大输出Token数量限制',
    enabled: true,
  },
  {
    key: 'enableStreamResponse',
    value: true,
    label: '流式响应',
    group: 'ai_settings',
    type: 'boolean',
    sort: 5,
    description: '是否开启流式响应（打字机效果）',
    enabled: true,
  },
  {
    key: 'enableSystemPrompt',
    value: true,
    label: '系统提示词',
    group: 'ai_settings',
    type: 'boolean',
    sort: 6,
    description: '是否允许用户配置系统提示词',
    enabled: true,
  },
  {
    key: 'defaultSystemPrompt',
    value: '你是一个有帮助的AI助手。',
    label: '默认系统提示词',
    group: 'ai_settings',
    type: 'string',
    sort: 7,
    description: '新用户默认的系统提示词',
    enabled: true,
  },

  // ============== Content Moderation ==============
  {
    key: 'enableContentModeration',
    value: true,
    label: '内容审核',
    group: 'content_settings',
    type: 'boolean',
    sort: 1,
    description: '是否开启内容安全审核',
    enabled: true,
  },
  {
    key: 'moderationSensitivity',
    value: 'medium',
    label: '审核敏感度',
    group: 'content_settings',
    type: 'string',
    sort: 2,
    description: '内容审核敏感度等级(low/medium/high)',
    enabled: true,
  },
  {
    key: 'blockSensitiveContent',
    value: true,
    label: '拦截敏感内容',
    group: 'content_settings',
    type: 'boolean',
    sort: 3,
    description: '是否直接拦截敏感内容，否则仅标记',
    enabled: true,
  },
  {
    key: 'enableUserReport',
    value: true,
    label: '用户举报',
    group: 'content_settings',
    type: 'boolean',
    sort: 4,
    description: '是否允许用户举报违规内容',
    enabled: true,
  },
  {
    key: 'autoBanThreshold',
    value: 3,
    label: '自动封禁阈值',
    group: 'content_settings',
    type: 'number',
    sort: 5,
    description: '用户被举报多少次后自动封禁',
    enabled: true,
  },

  // ============== UI Settings ==============
  {
    key: 'defaultTheme',
    value: 'auto',
    label: '默认主题',
    group: 'ui_settings',
    type: 'string',
    sort: 1,
    description: '新用户的默认主题设置(auto/light/dark)',
    enabled: true,
  },
  {
    key: 'showWelcomeGuide',
    value: true,
    label: '显示欢迎引导',
    group: 'ui_settings',
    type: 'boolean',
    sort: 2,
    description: '新用户首次登录是否显示欢迎引导页',
    enabled: true,
  },
  {
    key: 'enableAnnouncement',
    value: false,
    label: '系统公告',
    group: 'ui_settings',
    type: 'boolean',
    sort: 3,
    description: '是否显示系统公告弹窗',
    enabled: true,
  },
  {
    key: 'announcementContent',
    value: '',
    label: '公告内容',
    group: 'ui_settings',
    type: 'string',
    sort: 4,
    description: '系统公告的具体内容',
    enabled: true,
  },
  {
    key: 'defaultAvatarUrl',
    value: '',
    label: '默认头像',
    group: 'ui_settings',
    type: 'string',
    sort: 5,
    description: '新用户的默认头像图片地址',
    enabled: true,
  },
  {
    key: 'showPageWatermark',
    value: false,
    label: '页面水印',
    group: 'ui_settings',
    type: 'boolean',
    sort: 6,
    description: '是否在页面上显示用户水印',
    enabled: true,
  },
  {
    key: 'watermarkText',
    value: 'LobeHub',
    label: '水印文字',
    group: 'ui_settings',
    type: 'string',
    sort: 7,
    description: '水印显示的文字内容',
    enabled: true,
  },

  // ============== Security Settings ==============
  {
    key: 'sessionTimeoutMinutes',
    value: 30,
    label: '会话超时时间(分钟)',
    group: 'security_settings',
    type: 'number',
    sort: 1,
    description: '用户无操作多久后自动登出',
    enabled: true,
  },
  {
    key: 'passwordMinLength',
    value: 8,
    label: '密码最小长度',
    group: 'security_settings',
    type: 'number',
    sort: 2,
    description: '用户密码的最小长度要求',
    enabled: true,
  },
  {
    key: 'passwordRequireUppercase',
    value: false,
    label: '密码需大写字母',
    group: 'security_settings',
    type: 'boolean',
    sort: 3,
    description: '密码是否必须包含大写字母',
    enabled: true,
  },
  {
    key: 'passwordRequireNumber',
    value: false,
    label: '密码需数字',
    group: 'security_settings',
    type: 'boolean',
    sort: 4,
    description: '密码是否必须包含数字',
    enabled: true,
  },
  {
    key: 'passwordRequireSymbol',
    value: false,
    label: '密码需特殊字符',
    group: 'security_settings',
    type: 'boolean',
    sort: 5,
    description: '密码是否必须包含特殊字符',
    enabled: true,
  },
  {
    key: 'enableTwoFactor',
    value: false,
    label: '两步验证',
    group: 'security_settings',
    type: 'boolean',
    sort: 6,
    description: '是否开启两步验证功能',
    enabled: true,
  },
  {
    key: 'maxLoginAttempts',
    value: 5,
    label: '最大登录尝试次数',
    group: 'security_settings',
    type: 'number',
    sort: 7,
    description: '连续登录失败多少次后锁定账号',
    enabled: true,
  },
  {
    key: 'loginLockoutMinutes',
    value: 15,
    label: '登录锁定时间(分钟)',
    group: 'security_settings',
    type: 'number',
    sort: 8,
    description: '账号被锁定后多久自动解锁',
    enabled: true,
  },
  {
    key: 'enableIpWhitelist',
    value: false,
    label: 'IP白名单',
    group: 'security_settings',
    type: 'boolean',
    sort: 9,
    description: '是否启用管理员后台IP白名单限制',
    enabled: true,
  },
  {
    key: 'ipWhitelist',
    value: [],
    label: 'IP白名单列表',
    group: 'security_settings',
    type: 'json',
    sort: 10,
    description: '允许访问管理后台的IP地址列表',
    enabled: true,
  },

  // ============== Notification Settings ==============
  {
    key: 'enableEmailNotification',
    value: true,
    label: '邮件通知',
    group: 'notification_settings',
    type: 'boolean',
    sort: 1,
    description: '是否启用邮件通知',
    enabled: true,
  },
  {
    key: 'enableBrowserPush',
    value: true,
    label: '浏览器推送',
    group: 'notification_settings',
    type: 'boolean',
    sort: 2,
    description: '是否启用浏览器推送通知',
    enabled: true,
  },
  {
    key: 'notifyPaymentSuccess',
    value: true,
    label: '支付成功通知',
    group: 'notification_settings',
    type: 'boolean',
    sort: 3,
    description: '支付成功后是否发送通知',
    enabled: true,
  },
  {
    key: 'notifySubscriptionExpiry',
    value: true,
    label: '订阅到期提醒',
    group: 'notification_settings',
    type: 'boolean',
    sort: 4,
    description: '订阅到期前是否发送提醒',
    enabled: true,
  },
  {
    key: 'subscriptionExpiryDays',
    value: 3,
    label: '到期提前提醒(天)',
    group: 'notification_settings',
    type: 'number',
    sort: 5,
    description: '订阅到期前多少天开始发送提醒',
    enabled: true,
  },
  {
    key: 'notifyNewMessage',
    value: true,
    label: '新消息通知',
    group: 'notification_settings',
    type: 'boolean',
    sort: 6,
    description: '收到新消息时是否发送通知',
    enabled: true,
  },

  // ============== Storage Settings ==============
  {
    key: 'storageProvider',
    value: 'local',
    label: '存储提供商',
    group: 'storage_settings',
    type: 'string',
    sort: 1,
    description: '文件存储服务提供商(local/s3/oss/cos)',
    enabled: true,
  },
  {
    key: 'storageBucket',
    value: 'lobehub-files',
    label: '存储桶名称',
    group: 'storage_settings',
    type: 'string',
    sort: 2,
    description: 'S3/OSS/COS存储桶名称',
    enabled: true,
  },
  {
    key: 'storageRegion',
    value: '',
    label: '存储区域',
    group: 'storage_settings',
    type: 'string',
    sort: 3,
    description: '存储服务区域',
    enabled: true,
  },
  {
    key: 'fileExpiryDays',
    value: 0,
    label: '文件过期天数',
    group: 'storage_settings',
    type: 'number',
    sort: 4,
    description: '上传文件多少天后自动删除(0表示永不过期)',
    enabled: true,
  },
  {
    key: 'enableImageCompression',
    value: true,
    label: '图片压缩',
    group: 'storage_settings',
    type: 'boolean',
    sort: 5,
    description: '上传图片时是否自动压缩',
    enabled: true,
  },
  {
    key: 'imageCompressionQuality',
    value: 80,
    label: '图片压缩质量(%)',
    group: 'storage_settings',
    type: 'number',
    sort: 6,
    description: '图片压缩质量百分比',
    enabled: true,
  },

  // ============== Integration Settings ==============
  {
    key: 'enableGithubLogin',
    value: false,
    label: 'GitHub 登录',
    group: 'integration_settings',
    type: 'boolean',
    sort: 1,
    description: '是否启用GitHub第三方登录',
    enabled: true,
  },
  {
    key: 'enableGoogleLogin',
    value: false,
    label: 'Google 登录',
    group: 'integration_settings',
    type: 'boolean',
    sort: 2,
    description: '是否启用Google第三方登录',
    enabled: true,
  },
  {
    key: 'enableWechatLogin',
    value: false,
    label: '微信登录',
    group: 'integration_settings',
    type: 'boolean',
    sort: 3,
    description: '是否启用微信扫码登录',
    enabled: true,
  },
  {
    key: 'enableDingtalkLogin',
    value: false,
    label: '钉钉登录',
    group: 'integration_settings',
    type: 'boolean',
    sort: 4,
    description: '是否启用钉钉登录',
    enabled: true,
  },
  {
    key: 'enableLarkLogin',
    value: false,
    label: '飞书登录',
    group: 'integration_settings',
    type: 'boolean',
    sort: 5,
    description: '是否启用飞书登录',
    enabled: true,
  },
  {
    key: 'enableSlackIntegration',
    value: false,
    label: 'Slack 集成',
    group: 'integration_settings',
    type: 'boolean',
    sort: 6,
    description: '是否启用Slack消息集成',
    enabled: true,
  },

  // ============== Rate Limits ==============
  {
    key: 'apiRateLimitPerMinute',
    value: 60,
    label: 'API请求速率(次/分钟)',
    group: 'rate_limits',
    type: 'number',
    sort: 1,
    description: '每个用户每分钟最多API请求次数',
    enabled: true,
  },
  {
    key: 'chatRateLimitPerMinute',
    value: 30,
    label: '对话速率(次/分钟)',
    group: 'rate_limits',
    type: 'number',
    sort: 2,
    description: '每个用户每分钟最多发起对话次数',
    enabled: true,
  },
  {
    key: 'imageGenerateRateLimitPerDay',
    value: 50,
    label: '图片生成速率(次/天)',
    group: 'rate_limits',
    type: 'number',
    sort: 3,
    description: '每个用户每天最多图片生成次数',
    enabled: true,
  },
  {
    key: 'uploadRateLimitPerHour',
    value: 20,
    label: '文件上传速率(次/小时)',
    group: 'rate_limits',
    type: 'number',
    sort: 4,
    description: '每个用户每小时最多上传文件次数',
    enabled: true,
  },
];

/**
 * Seed default dictionary configurations into the database.
 * This is idempotent - existing keys are skipped, disabled configs are updated.
 * Returns summary of what was done.
 */
export const seedDictConfigs = async (
  db: LobeChatDatabase,
): Promise<{ total: number; created: number; updated: number; skipped: number }> => {
  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const config of DEFAULT_DICT_CONFIGS) {
    const [existing] = await db
      .select({
        id: dictConfigs.id,
        value: dictConfigs.value,
        label: dictConfigs.label,
        group: dictConfigs.group,
        type: dictConfigs.type,
        sort: dictConfigs.sort,
        description: dictConfigs.description,
        enabled: dictConfigs.enabled,
      })
      .from(dictConfigs)
      .where(eq(dictConfigs.key, config.key))
      .limit(1);

    if (!existing) {
      await db.insert(dictConfigs).values(config);
      created++;
    } else {
      const needsUpdate =
        existing.label !== config.label ||
        existing.group !== config.group ||
        existing.type !== config.type ||
        existing.sort !== config.sort ||
        existing.description !== config.description ||
        existing.enabled !== config.enabled;

      if (needsUpdate) {
        await db
          .update(dictConfigs)
          .set({
            label: config.label,
            group: config.group,
            type: config.type,
            sort: config.sort,
            description: config.description,
            enabled: config.enabled,
          })
          .where(eq(dictConfigs.id, existing.id));
        updated++;
      } else {
        skipped++;
      }
    }
  }

  return {
    total: DEFAULT_DICT_CONFIGS.length,
    created,
    updated,
    skipped,
  };
};
